# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.4.6
_src_path: https://github.com/epics-containers/ioc-template
description: Generic IOC definition for common support libraries including Asyn
git_platform: github.com
github_org: epics-containers
name: ioc-asyn
repo_uri: git@github.com:epics-containers/ioc-asyn.git
rtems: false
